server:
  port: 8760

eureka:
  instance:
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8888/eureka # discovery service location

spring:
  application:
    name: ws-gateway # gateway service name to be called by it clients
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # use netflix eureka discovery service
      routes:
        - id: ws-server
          uri: lb://ws-server # netflix eureka correspondent service
          predicates:
            - After=2022-01-20T17:42:47.789-07:00[America/Denver]
